### ISSUE TITLE
Мониторинг сайтов из списка конфигов

### ISSUE THREAD

**Issue by vlegio** [jtprogru/sitemon#2]
## Реализовать чекер сайтов:
* На входе url, timeout, на выходе error
* Покрыть тестами
* Используем только стандартную библиотеку

Пример входных данных:
```yaml
  jtprog:  # Имя объекта в рамках конфига, должно отображаться в алертах
    method: "GET"  # HTTP метод для осуществления запроса
    url: "https://jtprog.ru"  # URL начинающийся со схемы
    timeout: 15  # Таймаут на получение ответа от сервера
    check_every: 60  # Раз в сколько секунд выполнять проверку данного ресурса
```

URL для проверки может быть задан в нескольких форматах:
- `url: "https://jtprog.ru"` – с указанием схемы (указана схема и порт для подключения берется дефолтный для данной схемы);
- `url: "http://jtprog.ru"` – с указанием схемы (указана схема и порт для подключения берется дефолтный для данной схемы);
- `url: "https://jtprog.ru:8443"` – с указанием схемы и порта;
- `url: "http://jtprog.ru:8080"` – с указанием схемы и порта;
- `url: "jtprog.ru"` – без указания схемы и порта (должны использоваться дефолтные схема HTTP и порт 80);

Сайт считается доступным, если:
- После цепочки редиректов  отдает НЕ  http код `200 OK`
- Максимальное количество редиректов должно быть ограничено 10 (десятью), но предусмотреть возможность расширения через конфиг
