### ISSUE TITLE
Все настройки только в конфиге

### ISSUE THREAD

**Issue by jtprogru** [jtprogru/sitemon#9]
Реализовать функционал считывания YAML-файла с конфигурацией. Пример файла указан в [README.md](https://github.com/bearonserver/sitemon/blob/master/README.md).

## Основные составляющие конфигурационного файла
Настройка уровня логирования и формата логов:
```yaml
log:
  level: "DEBUG"
  format: "[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s"
```
Интеграция в Sentry:
```yaml
sentry:
  dsn: "https://1231231231231231231238cc0375b556@o412493.ingest.sentry.io/5383803"
```
Интеграция с Telegram:
```yaml
telegram:
  token: "123456789:qwertyuiopasdfghjkzxcvbnm"
  chat: "-12123123123"
```
Список объектов для мониторинга:
```yaml
monitors:
  jtprog:
    method: "GET"
    url: "https://jtprog.ru"
    timeout: 15
    check_every: 60

  httpbin:
    method: "GET"
    url: "https://httpbin.org/get"
    timeout: 5
    check_every: 90
```

## На что стоит обращать внимание
На этапе реализации функционала считывания конфигурационного файла, не стоит забывать про переменные окружения. Если какой-либо параметр передан через переменные окружения на этапе запуска приложения, то переданное значение должно переопределять значение из конфигурационного файла.

Среди переменных окружения стоит хранить следующие данные/значения:
- `SITEMON_LOGLEVEL` – переменная окружения определяет уровень логирования;
- `SITEMON_SENTRYDSN` – переменная окружения определяет DSN для сервиса Sentry (куда будут отправляться все ошибки приложения);
- `SITEMON_TGTOKEN` – переменная окружения определяет токен для Telegram-бота;
- `SITEMON_TGCHAT` – переменная окружения определяет ID Telegram-чата куда будут отправляться сообщения;

Все переменные окружения должны начинаться с префикса `SITEMON_`.
